"""
Demo endpoint
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional
from app.services.demo_orchestrator import DemoOrchestrator

router = APIRouter()
orchestrator = DemoOrchestrator()

@router.post("/demo/trigger")
async def trigger_demo(campaign_id: str, intensity: int = 5):
    """Trigger a demo campaign with specified intensity (1-10)"""
    try:
        result = orchestrator.trigger_campaign(campaign_id, intensity)
        if "error" in result:
            raise HTTPException(status_code=400, detail=result["error"])
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error triggering campaign: {str(e)}")

@router.get("/demo/campaigns")
async def list_campaigns():
    """List available campaign templates"""
    return {
        "campaigns": list(orchestrator.campaign_templates.keys()),
        "templates": orchestrator.campaign_templates
    }

@router.get("/demo/status/{campaign_instance_id}")
async def get_campaign_status(campaign_instance_id: str):
    """Get status of a specific campaign"""
    try:
        result = orchestrator.get_campaign_status(campaign_instance_id)
        if "error" in result:
            raise HTTPException(status_code=404, detail=result["error"])
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error getting campaign status: {str(e)}")

@router.get("/demo/active")
async def list_active_campaigns():
    """List all active campaigns"""
    try:
        return {"active_campaigns": orchestrator.list_active_campaigns()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error listing campaigns: {str(e)}")

@router.post("/demo/stop/{campaign_instance_id}")
async def stop_campaign(campaign_instance_id: str):
    """Stop a running campaign"""
    try:
        result = orchestrator.stop_campaign(campaign_instance_id)
        if "error" in result:
            raise HTTPException(status_code=404, detail=result["error"])
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error stopping campaign: {str(e)}")

@router.get("/demo/events/{campaign_instance_id}")
async def get_campaign_events(campaign_instance_id: str):
    """Get events generated by a campaign"""
    try:
        events = orchestrator.generate_campaign_events(campaign_instance_id)
        return {
            "campaign_instance_id": campaign_instance_id,
            "events": events,
            "count": len(events)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error getting campaign events: {str(e)}")